### ISSUE TITLE
Install_honeymap installation script broken

### ISSUE THREAD

**Issue by mercolino** [threatstream/mhn#129]
install_honeymap script is broken after the last push, it fails with an error:

go install: no install location for directory /opt/honeymap/server outside GOPATH

Removing set -e  and set -x the script works....

**Comment by jt6211** [comment]
Thanks. will fix.  I believe it is the `set -e`

**Comment by mcmasterathl** [comment]
This issue appears to be because the "go build" step is trying to install a binary to GOBIN, which is not defined. Adding this:

export GOBIN=`pwd`

before the go build seems to fix it. I'm doing some other strange custom things too so I don't want to submit a PR in case that working depends on something else I'm doing, though.

Hope that helps.
