### ISSUE TITLE
Updating hpfeeds channels when upgrading installed mhn server.

### ISSUE THREAD

**Issue by sidra-asa** [threatstream/mhn#139]
I've noticed that channels in hpfeeds broker are not updated when updating old version mhn server. I tried to find instructions in wiki, but I can’t. So here's the script for upgrading installed mhn server:

```bash
#!/bin/bash

	set -e
	set -x

	# update the hpfeeds channels used by mnemosyne
	. /opt/hpfeeds/env/bin/activate

	IDENT=mnemosyne
	SECRET=`python -c "import pymongo;print pymongo.MongoClient().hpfeeds.auth_key.find({'identifier':'$IDENT'},{'secret':'1','_id':0})[0]"|grep -o "[a-z0-9]\{32\}"`
	SUBSCRIBE_CHAN='amun.events,conpot.events,thug.events,beeswarm.hive,dionaea.capture,dionaea.connections,thug.files,beeswarn.feeder,cuckoo.analysis,kippo.sessions,glastopf.events,glastopf.files,mwbinary.dionaea.sensorunique,snort.alerts,wordpot.events,p0f.events,suricata.events,shockpot.events'

	python /opt/hpfeeds/broker/add_user.py "$IDENT" "$SECRET" "" "$SUBSCRIBE_CHAN"

	unset IDENT
	unset SECRET
	unset SUBSCRIBE_CHAN

	# update the hpfeeds channels used by honeymap

	IDENT=honeymap
	SECRET=`python -c "import pymongo;print pymongo.MongoClient().hpfeeds.auth_key.find({'identifier':'$IDENT'},{'secret':'1','_id':0})[0]"|grep -o "[a-z0-9]\{32\}"`
	SUBSCRIBE_CHAN='geoloc.events'

	python /opt/hpfeeds/broker/add_user.py "$IDENT" "$SECRET" "" "$SUBSCRIBE_CHAN"

	unset IDENT
	unset SECRET
	unset SUBSCRIBE_CHAN

	# update the hpfeeds channels used by geoloc

	IDENT=geoloc
	SECRET=`python -c "import pymongo;print pymongo.MongoClient().hpfeeds.auth_key.find({'identifier':'$IDENT'},{'secret':'1','_id':0})[0]"|grep -o "[a-z0-9]\{32\}"`
	PUBLISH_CHAN='geoloc.events'
	SUBSCIRBE_CHAN='amun.events,dionaea.connections,dionaea.capture,glastopf.events,beeswarm.hive,kippo.sessions,conpot.events,snort.alerts,kippo.alerts,wordpot.events,shockpot.events,p0f.events,suricata.events'

	python /opt/hpfeeds/broker/add_user.py "$IDENT" "$SECRET" "$PUBLISH_CHAN" "$SUBSCIRBE_CHAN"

	unset IDENT
	unset SECRET
	unset PUBLISH_CHAN
	unset SUBSCIRBE_CHAN

	# update the hpfeeds channels used by collector

	IDENT=collector
	SECRET=`python -c "import pymongo;print pymongo.MongoClient().hpfeeds.auth_key.find({'identifier':'$IDENT'},{'secret':'1','_id':0})[0]"|grep -o "[a-z0-9]\{32\}"`
	SUBSCRIBE_CHAN='geoloc.events'

	python /opt/hpfeeds/broker/add_user.py "$IDENT" "$SECRET" "$PUBLISH_CHAN" "$SUBSCIRBE_CHAN"

	unset IDENT
	unset SECRET
	unset SUBSCIRBE_CHAN

	deactivate

	supervisorctl reload
```

Any feedbacks are welcomed.

**Comment by jt6211** [comment]
@sidra-asa thanks for sharing this.  I think this is close to what is needed, but I think this may cause some issues since it looks like it will create duplicate users (based on "identifier") which could cause issues with the hpfeeds broker not working as expected.

To do this right I believe we would need to update the record in mongo instead of calling `add_user.py` which adds a new record.

**Comment by sidra-asa** [comment]
@jt6211 In add_user.py, instead of using insert method, update method is used. Therefore, I think this may not cause the problem of creating duplicate users. I'v done some tests, and the results seems okay. Please let me know if you found any other problem. Thanks.

**Comment by jt6211** [comment]
@sidra-asa you're right, I should have looked closer at that script.  

This script looks good.  Some feedback:

It would probably make sense to just create a script called get_secret.py and call it each time instead of having the python code replicated in each place.

There are a couple of variables that are inconsistently named:
SUBSCIRBE_CHAN vs SUBSCRIBE_CHAN

Lastly, it would probably be a good idea for each of these subscribe/publish lists to be maintained in a single config file and this script could reference that file.

**Comment by sidra-asa** [comment]
@jt6211 Thanks for the feedback. I'll work on it.

**Comment by jt6211** [comment]
https://github.com/threatstream/mhn/pull/160
