### ISSUE TITLE
Best procedure to backup

### ISSUE THREAD

**Issue by gbrindisi** [threatstream/mhn#210]
Hi,
what's the best way to backup the MHN server and sensors?

**Comment by jt6211** [comment]
I just added a new wiki page for backing up and restoring MHN: https://github.com/threatstream/mhn/wiki/Backing-Up-and-Restoring-MHN.

The sensors are a lot more challenging to backup and restore since it is often sensor specific.  It is often easily to just wipe them and redeploy using MHN deploy scripts.

**Comment by gbrindisi** [comment]
Thank you, didn't notice it.
