### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by kayaaaba** [threatstream/mhn#288]
How do we generate log files and how do we get them in "attacks report"?

**Comment by jt6211** [comment]
If you have deployed honeypots and they are seeing traffic you should see events in the attacks page of MHN.  If you want log files you can setup hpfeeds-logger.  See the files with these names in /opt/mhn/scripts/

install_hpfeeds-logger-arcsight.sh
install_hpfeeds-logger-json.sh
install_hpfeeds-logger-splunk.sh

**Comment by kayaaaba** [comment]
Hpfeeds-logger doesn`t setup by defauly?

To say correct, I`m interested in  which command creates the log files in deployed honeypots

**Comment by jt6211** [comment]
Hpfeeds-logger is designed to log honeypot events so they can be used in
external systems like siems or log management solutions. It is not enabled
by default since not everyone cares about this.

On Friday, July 1, 2016, kayaaaba <notifications@github.com> wrote:

> Hpfeeds-logger doesn`t setup by defauly?
>
> To say correct, I`m interested in which command creates the log files in
> deployed honeypots
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/threatstream/mhn/issues/288#issuecomment-230058416>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAyE8EHRTtyuAlFWlzth6mDb0LaN1pK9ks5qRZBjgaJpZM4JDV97>
> .
>


-- 
Jason Trost | VP of Threat Research | www.anomali.com
2317 Broadway, 3rd Floor| Redwood City, CA 94063
Phone:  386.235.0078 | Twitter:  @jason_trost

<https://www.anomali.com/anomali-detect>

**Comment by kayaaaba** [comment]
I do care.
Can you answer yhe question please?
I`m interested in which command creates the log files in deployed honeypots?

**Comment by sh4t** [comment]
@kayaaaba to clarify what @jt6211 is pointing out is that mhn ships with the bash scripts you can leverage to provide what you care about and are inquiring for.

in the scripts/ directory you will find numerous scripts related to hpfeeds; which is the service leveraged by both the honey pot side and MHN to provide *log generation* related to the honey pot events you're wanting to collect.

Within those bash scripts you will find the individual commands and assets required.
