### ISSUE TITLE
Cowrie root user and password not shown!

### ISSUE THREAD

**Issue by Philelis** [threatstream/mhn#375]
I have the problem that I don't see the passwords for the root user in Cowrie graphs, same for Kibana, BUT I can see it in the Mongo DB logs.
`{ "_id" : ObjectId(""), "protocol" : "ssh", "hpfeed_id" : ObjectId(""), "timestamp" : ISODate("2017-03-07T12:49:23.187Z"), "source_ip" : "192.168.122.182", "session_ssh" : { "version" : "SSH-2.0-OpenSSH_6.6.1" }, "source_port" : 48904, "destination_port" : 2222, "identifier" : "", "honeypot" : "cowrie", "auth_attempts" : [ { "login" : "root", "password" : "why" } ] }`

For another User it looks like:
`{ "_id" : ObjectId(""), "protocol" : "ssh", "hpfeed_id" : ObjectId(""), "timestamp" : ISODate("2017-03-07T12:48:50.081Z"), "source_ip" : "192.168.122.182", "session_ssh" : { "version" : "SSH-2.0-OpenSSH_6.6.1" }, "source_port" : 48838, "destination_port" : 2222, "identifier" : "", "honeypot" : "cowrie", "auth_attempts" : [ { "login" : "phil", "password" : "phil" }, { "login" : "phil", "password" : "123" } ] }
`

![2017-03-07-135624_1089x745_scrot](https://cloud.githubusercontent.com/assets/9850839/23657370/fda0a420-033d-11e7-9f12-935261475663.png)

Has anyone the same problem, is it normal, could someone help me?

I have tested it on two pcs with CentOS 7.

**Comment by jt6211** [comment]
It is likely that this user/pass combination is not showing up b/c it is
not as frequent as the user/pass.  These charts don't show all the
user/pass, only the top ones

On Tue, Mar 7, 2017 at 7:59 AM, Philelis <notifications@github.com> wrote:

I have the problem that I don't see the passwords for the root user in
Cowrie graphs, same for Kibana, BUT I can see it in the Mongo DB logs.
{ "_id" : ObjectId(""), "protocol" : "ssh", "hpfeed_id" : ObjectId(""),
"timestamp" : ISODate("2017-03-07T12:49:23.187Z"), "source_ip" :
"192.168.122.182", "session_ssh" : { "version" : "SSH-2.0-OpenSSH_6.6.1" },
"source_port" : 48904, "destination_port" : 2222, "identifier" : "",
"honeypot" : "cowrie", "auth_attempts" : [ { "login" : "root", "password" :
"why" } ] }

[image: 2017-03-07-135624_1089x745_scrot]
<https://cloud.githubusercontent.com/assets/9850839/23657370/fda0a420-033d-11e7-9f12-935261475663.png>

Has anyone the same problem, is it normal, could someone help me?

I have tested it on two pcs with CentOS 7.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/threatstream/mhn/issues/375>, or mute the thread

**Comment by Philelis** [comment]
Yeah thats clear, but I tested it with root before another user was here, but it did not appeared in the graphs or in Kibana. In Kibana I "only" saw the commands and other stuff from my attack, but not one user or password.

**Comment by Philelis** [comment]
Oh I found the problem, it works if you try with password that don't work, others are excluded.

**Comment by Philesiv** [comment]
Is there any way to show all the user/password combinations in mhn, especially the working ones?
Or maybe only the working ones?

**Comment by Waseem-farooqui** [comment]
On the dashboard I don't think its possible but you can query your database If you just want to see the successful passwords are the most common used password.

**Comment by Sue1990** [comment]
@Philelis where can find error messages?
