### ISSUE TITLE
can't deploy my honeypot

### ISSUE THREAD

**Issue by AFTAHI** [threatstream/mhn#400]
hi i'm new with the honeynet project and i'm using virtual machines on my laptop to test the honeynet system. i set up the mhn server properly but when i copy the link to deploy the honeypot in my virtual machine where i wanna deploy the honeypot i can't connect and said connection refused.
can any one help me that please?

**Comment by bflew** [comment]
I have the same issue, i changed the ip address to mhn.threatstream.com and it downloaded the files but threw a exception at the end for all the deployment scripts

**Comment by bflew** [comment]
i will fall back on Ubuntu 12 as other version aren't tested or supported and get back

**Comment by bflew** [comment]
Tested on Ubuntu 12 and throws same error

**Comment by haha5566** [comment]
If you use VirtualBox.Try to set Port Forwarding?

**Comment by Waseem-farooqui** [comment]
Ping the mhn server ip from the vm where you want to deploy the honeypot.
I think it would be becz of `nat` and `bridging` stuff.

**Comment by bflew** [comment]
i could not ping the ip address from my pc or my vm, i can only ping mhn.threatstream.com, so i replace the ip the the url but the install fails. I dont think the ip address is up.

**Comment by bflew** [comment]
IP Address is http://24.114.71.239/

**Comment by bflew** [comment]
I also get this when i use mhn.threatstream.com instead of the ip

++ curl -s -X POST -H 'Content-Type: application/json' -d '{
	"name": "ubuntu-p0f", 
	"hostname": "ubuntu", 
	"deploy_key": "WhqqW4U7",
	"honeypot": "p0f"
}' http://mhn.threatstream.com/api/sensor/
+++ python -c 'import json;obj=json.load(file("/tmp/deploy.json"));print obj["uuid"]'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
++ uuid=
anon@ubuntu:~$ wget "http://24.114.71.239/api/script/?text=true&script_id=9" -O deploy.sh && sudo bash deploy.sh http://24.114.71.239 WhqqW4U7
--2017-05-20 11:00:05--  http://24.114.71.239/api/script/?text=true&script_id=9
Connecting to 24.114.71.239:80... failed: Connection refused.

**Comment by bflew** [comment]
i figured it out, since i didnt have a static ip, the deploy script ip was wrong, i set it to my vm box ip and it works
