### ISSUE TITLE
Error on hpfeeds-broker after clean install

### ISSUE THREAD

**Issue by alexforero** [threatstream/mhn#431]
Hello,

I have followed guide to install MHN (git clone, sudo install.sh) on ubuntu 14.

After installation i have checked:

root@ip-172-31-38-XXX:/opt/mhn# supervisorctl status
geoloc                           RUNNING    pid 323, uptime 0:23:14
honeymap                         RUNNING    pid 329, uptime 0:23:14
hpfeeds-broker                   FATAL      Exited too quickly (process log may have details)
mhn-celery-beat                  RUNNING    pid 1874, uptime 0:04:48
mhn-celery-worker                RUNNING    pid 1926, uptime 0:04:35
mhn-collector                    RUNNING    pid 1878, uptime 0:04:48
mhn-uwsgi                        RUNNING    pid 1891, uptime 0:04:48
mnemosyne                        RUNNING    pid 31042, uptime 0:24:26
root@ip-172-31-38-XXX:/opt/mhn#

If I check error log:

root@ip-172-31-38-XXX:/opt/mhn# cat /var/log/mhn/hpfeeds-broker.err
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Someone could help me?

Thank you in advance,

**Comment by Ge3kySaint29** [comment]
I am having the same issue at the moment. I am going to try and update and upgrade all my packages in Ubuntu to see if that solves the problem.

**Comment by Ge3kySaint29** [comment]
After looking into the issue it seems like mongodb service is disabled. 

● mongodb.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/etc/systemd/system/mongodb.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2016-04-25 14:57:20 EDT; 1min 30s ago
 Main PID: **** (mongod)
   CGroup: /system.slice/mongodb.service
           └─**** /usr/bin/mongod --quiet --config /etc/mongod.conf

Tried running sudo start mongodb.service but I am failing to connect to Upstart. The error message is...

*start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

Working on solution now...

**Comment by Ge3kySaint29** [comment]
After further investigating and updating everything, I noticed that mongodb was disabled first. I went ahead enabled it, restarted all the processes, and I am still coming up short...What I cannot figure out is my mongodb.service and why it cannot connect to Upstart..

root@root-VirtualBox:~$ sudo systemctl status mongodb
● mongodb.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/etc/systemd/system/mongodb.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-07-18 09:27:17 CDT; 1h 40min ago
 Main PID: 18761 (mongod)
   CGroup: /system.slice/mongodb.service
           └─18761 /usr/bin/mongod --quiet --config /etc/mongod.conf

Jul 18 09:27:17 winnie-VirtualBox systemd[1]: Started High-performance, schema-free document-oriented database.
Jul 18 09:27:58 winnie-VirtualBox systemd[1]: Started High-performance, schema-free document-oriented database.
Jul 18 09:48:36 winnie-VirtualBox systemd[1]: Started High-performance, schema-free document-oriented database.
Jul 18 09:51:47 winnie-VirtualBox systemd[1]: Started High-performance, schema-free document-oriented database.
Jul 18 09:52:14 winnie-VirtualBox systemd[1]: Started High-performance, schema-free document-oriented database.
root@root-VirtualBox:~$ sudo supervisorctl restart all
honeymap: stopped
mnemosyne: stopped
geoloc: stopped
mhn-collector: stopped
mhn-celery-beat: stopped
mhn-uwsgi: stopped
mhn-celery-worker: stopped
hpfeeds-broker: ERROR (spawn error)
mhn-celery-beat: started
honeymap: started
mnemosyne: started
geoloc: started
mhn-uwsgi: started
mhn-celery-worker: started
mhn-collector: started
root@root-VirtualBox:~$ cd /var/log/mhn/
root@root-VirtualBox:/var/log/mhn$ ls
geoloc.err  honeymap.err  hpfeeds-broker.err  mhn-celery-beat.err  mhn-celery-worker.err  mhn-collector.err  mhn.log        mhn-uwsgi.log  mnemosyne.log
geoloc.log  honeymap.log  hpfeeds-broker.log  mhn-celery-beat.log  mhn-celery-worker.log  mhn-collector.log  mhn-uwsgi.err  mnemosyne.err  mnemosyne.out
winnie@winnie-VirtualBox:/var/log/mhn$ tail hpfeeds-broker.err
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/feedbroker.py", line 13, in <module>
    from evnet import loop, unloop, listenplain, EventGen
  File "/opt/hpfeeds/env/src/evnet/evnet/__init__.py", line 11, in <module>
    from OpenSSL import SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
root@root-VirtualBox:~$ sudo status mongodb.service
status: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

**Comment by AVGirl** [comment]
sudo  /opt/hpfeeds/env/bin/python -m pip install --upgrade pyopenssl

**Comment by alexforero** [comment]
After apply AVGirl workarround it worked to me:

root@ip-172-31-:/opt/mhn# sudo /opt/hpfeeds/env/bin/python -m pip install --upgrade pyopenssl
/opt/hpfeeds/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/opt/hpfeeds/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting pyopenssl
  Downloading pyOpenSSL-17.1.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 1.9MB/s
Requirement already up-to-date: six>=1.5.2 in /opt/hpfeeds/env/lib/python2.7/site-packages (from pyopenssl)
Requirement already up-to-date: cryptography>=1.9 in /opt/hpfeeds/env/lib/python2.7/site-packages (from pyopenssl)
Requirement already up-to-date: asn1crypto>=0.21.0 in /opt/hpfeeds/env/lib/python2.7/site-packages (from cryptography>=1.9->pyopenssl)
Requirement already up-to-date: enum34 in /opt/hpfeeds/env/lib/python2.7/site-packages (from cryptography>=1.9->pyopenssl)
Requirement already up-to-date: ipaddress in /opt/hpfeeds/env/lib/python2.7/site-packages (from cryptography>=1.9->pyopenssl)
Requirement already up-to-date: cffi>=1.7 in /opt/hpfeeds/env/lib/python2.7/site-packages (from cryptography>=1.9->pyopenssl)
Requirement already up-to-date: idna>=2.1 in /opt/hpfeeds/env/lib/python2.7/site-packages (from cryptography>=1.9->pyopenssl)
Requirement already up-to-date: pycparser in /opt/hpfeeds/env/lib/python2.7/site-packages (from cffi>=1.7->cryptography>=1.9->pyopenssl)
Installing collected packages: pyopenssl
  Found existing installation: pyOpenSSL 0.14
    Uninstalling pyOpenSSL-0.14:
      Successfully uninstalled pyOpenSSL-0.14
Successfully installed pyopenssl-17.1.0
root@ip-172-31-:/opt/mhn# supervisorctl restart all
mhn-celery-beat: stopped
honeymap: stopped
mnemosyne: stopped
geoloc: stopped
mhn-uwsgi: stopped
mhn-celery-worker: stopped
mhn-collector: stopped
mhn-celery-beat: started
honeymap: started
mnemosyne: started
geoloc: started
mhn-uwsgi: started
mhn-celery-worker: started
mhn-collector: started
hpfeeds-broker: started
root@ip-172-31:/opt/mhn# supervisorctl status
geoloc                           RUNNING    pid 546, uptime 0:00:31
honeymap                         RUNNING    pid 532, uptime 0:00:31
hpfeeds-broker                   RUNNING    pid 569, uptime 0:00:29
mhn-celery-beat                  RUNNING    pid 531, uptime 0:00:31
mhn-celery-worker                RUNNING    pid 557, uptime 0:00:30
mhn-collector                    RUNNING    pid 562, uptime 0:00:29
mhn-uwsgi                        RUNNING    pid 552, uptime 0:00:30
mnemosyne                        RUNNING    pid 539, uptime 0:00:31
root@ip-172-31-:/opt/mhn#
