### ISSUE TITLE
How can I get username/password to login MHN ?

### ISSUE THREAD

**Issue by BhautikRamani** [threatstream/mhn#492]
I need login credentials for mhn...

**Comment by kont45** [comment]
You created credentials during install MHN server. Just check "configuration" section: https://github.com/threatstream/mhn 
But if you have to reset login and password: https://github.com/threatstream/mhn/wiki/Password-Reset-Without-Web-UI

**Comment by haddey** [comment]
I forgot to put username and password during MHN configuration. now i cant log in to MHN, what should i do?

**Comment by npkllr** [comment]
Try `root@localhost` as email and `password` as password.

---

If you know the email, but not the password, execute as root on the host where MHN is running:
```
cd /opt/mhn
source env/bin/activate
python server/manual_password_reset.py
```
You will be asked to enter your email and a new password.

---

If `root@localhost` does not work, follow [this guide](https://github.com/pwnlandia/mhn/wiki/MHN-Troubleshooting-Guide#i-cant-reset-my-password-because-i-fat-fingered-the-email-during-the-install) to reset the email.
