### ISSUE TITLE
Honeypot Combination?

### ISSUE THREAD

**Issue by helience** [threatstream/mhn#536]
Hello, 

I need some advice from you all, I want to try Modern Honey Network on Virtual Machine for some test and will implement it to Virtual Private Server. the sensors that I want to install : 

MHN, Cowrie, Snort, Dionaea and Conpot. 

I just read some information that some combination of honeypots will works well, but I just only found Snort + Cowrie in the MHN Wiki. Can I get any advices about the combination that will decrease the use of the machine/VPS? also I will use the HoneyMap as well.

Tried all that 5 honeypots on 1 machine, the conpot isn't working but the MHN is working fine, 
then tried Conpot on a different machine/VPS with a local connection to MHN and both have different public IP, all the sensors works well but HoneyMap never get any info about the new attacks while the sensors always get it. 

any advices? thank you and sorry for my bad English

**Comment by zshehri** [comment]
Hi, indeed you can install multiple honeypot services on one VPS, here are some [use cases](https://www.anomali.com/platform/modern-honey-net/mhn-usage-cases). (_replace Kippo with Cowrie and you should be good to go_!) 

Conpot wasn't working because it listens to port 80, and it seems MHN uses that port already ([reference](https://github.com/threatstream/mhn/wiki/Running-Multiple-Honeypots-on-the-same-server)).

One thing I would highly recommend that you **install MHN on a separate VPS**. The main reason is to avoid any simultaneous use of the same port(s) & to reduce the load on your MHN server.

Also, you don't want the attackers to target your honeypots & the MHN server!

**Comment by d1str0** [comment]
@zshehri is correct. It's a matter of hosting all the different services all on one box. If the ports don't collide, you're technically fine, but it's not recommended as it is high load and you don't necessarily want your MHN box as open and vulnerable to the web as your honeypots.

These honeypots may not be 100% secure as they are supposed to be attacked.

**Comment by helience** [comment]
thank you, just found a best way to combine this honeypot
